//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastro_Angular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa_Juridica
    {
        public int Id { get; set; }
        public string RAZAO_SOCIAL { get; set; }
        public string NOME_FANTASIA { get; set; }
        public Nullable<int> CNPJ { get; set; }
        public Nullable<int> CEP1 { get; set; }
        public string LOGRADOURO { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
    }
}
