//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastro_Angular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa_Fisica
    {
        public int id { get; set; }
        public string NOME { get; set; }
        public string SOBRENOME { get; set; }
        public Nullable<int> CPF { get; set; }
        public Nullable<System.DateTime> DATA_NASCIMENTO { get; set; }
        public Nullable<int> CEP { get; set; }
        public string LOGRADOURO { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
    }
}
